# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mike/Downloads/mini-caffe-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mike/Downloads/mini-caffe-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/Downloads/mini-caffe-master/CMakeFiles /home/mike/Downloads/mini-caffe-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/Downloads/mini-caffe-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named caffe

# Build rule for target.
caffe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caffe
.PHONY : caffe

# fast build rule for target.
caffe/fast:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/build
.PHONY : caffe/fast

src/blob.o: src/blob.cpp.o

.PHONY : src/blob.o

# target to build an object file
src/blob.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/blob.cpp.o
.PHONY : src/blob.cpp.o

src/blob.i: src/blob.cpp.i

.PHONY : src/blob.i

# target to preprocess a source file
src/blob.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/blob.cpp.i
.PHONY : src/blob.cpp.i

src/blob.s: src/blob.cpp.s

.PHONY : src/blob.s

# target to generate assembly for a file
src/blob.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/blob.cpp.s
.PHONY : src/blob.cpp.s

src/c_api.o: src/c_api.cpp.o

.PHONY : src/c_api.o

# target to build an object file
src/c_api.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/c_api.cpp.o
.PHONY : src/c_api.cpp.o

src/c_api.i: src/c_api.cpp.i

.PHONY : src/c_api.i

# target to preprocess a source file
src/c_api.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/c_api.cpp.i
.PHONY : src/c_api.cpp.i

src/c_api.s: src/c_api.cpp.s

.PHONY : src/c_api.s

# target to generate assembly for a file
src/c_api.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/c_api.cpp.s
.PHONY : src/c_api.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/layer_factory_.o: src/layer_factory_.cpp.o

.PHONY : src/layer_factory_.o

# target to build an object file
src/layer_factory_.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layer_factory_.cpp.o
.PHONY : src/layer_factory_.cpp.o

src/layer_factory_.i: src/layer_factory_.cpp.i

.PHONY : src/layer_factory_.i

# target to preprocess a source file
src/layer_factory_.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layer_factory_.cpp.i
.PHONY : src/layer_factory_.cpp.i

src/layer_factory_.s: src/layer_factory_.cpp.s

.PHONY : src/layer_factory_.s

# target to generate assembly for a file
src/layer_factory_.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layer_factory_.cpp.s
.PHONY : src/layer_factory_.cpp.s

src/layers/absval_layer.o: src/layers/absval_layer.cpp.o

.PHONY : src/layers/absval_layer.o

# target to build an object file
src/layers/absval_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/absval_layer.cpp.o
.PHONY : src/layers/absval_layer.cpp.o

src/layers/absval_layer.i: src/layers/absval_layer.cpp.i

.PHONY : src/layers/absval_layer.i

# target to preprocess a source file
src/layers/absval_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/absval_layer.cpp.i
.PHONY : src/layers/absval_layer.cpp.i

src/layers/absval_layer.s: src/layers/absval_layer.cpp.s

.PHONY : src/layers/absval_layer.s

# target to generate assembly for a file
src/layers/absval_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/absval_layer.cpp.s
.PHONY : src/layers/absval_layer.cpp.s

src/layers/argmax_layer.o: src/layers/argmax_layer.cpp.o

.PHONY : src/layers/argmax_layer.o

# target to build an object file
src/layers/argmax_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/argmax_layer.cpp.o
.PHONY : src/layers/argmax_layer.cpp.o

src/layers/argmax_layer.i: src/layers/argmax_layer.cpp.i

.PHONY : src/layers/argmax_layer.i

# target to preprocess a source file
src/layers/argmax_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/argmax_layer.cpp.i
.PHONY : src/layers/argmax_layer.cpp.i

src/layers/argmax_layer.s: src/layers/argmax_layer.cpp.s

.PHONY : src/layers/argmax_layer.s

# target to generate assembly for a file
src/layers/argmax_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/argmax_layer.cpp.s
.PHONY : src/layers/argmax_layer.cpp.s

src/layers/base_conv_layer.o: src/layers/base_conv_layer.cpp.o

.PHONY : src/layers/base_conv_layer.o

# target to build an object file
src/layers/base_conv_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/base_conv_layer.cpp.o
.PHONY : src/layers/base_conv_layer.cpp.o

src/layers/base_conv_layer.i: src/layers/base_conv_layer.cpp.i

.PHONY : src/layers/base_conv_layer.i

# target to preprocess a source file
src/layers/base_conv_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/base_conv_layer.cpp.i
.PHONY : src/layers/base_conv_layer.cpp.i

src/layers/base_conv_layer.s: src/layers/base_conv_layer.cpp.s

.PHONY : src/layers/base_conv_layer.s

# target to generate assembly for a file
src/layers/base_conv_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/base_conv_layer.cpp.s
.PHONY : src/layers/base_conv_layer.cpp.s

src/layers/batch_norm_layer.o: src/layers/batch_norm_layer.cpp.o

.PHONY : src/layers/batch_norm_layer.o

# target to build an object file
src/layers/batch_norm_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/batch_norm_layer.cpp.o
.PHONY : src/layers/batch_norm_layer.cpp.o

src/layers/batch_norm_layer.i: src/layers/batch_norm_layer.cpp.i

.PHONY : src/layers/batch_norm_layer.i

# target to preprocess a source file
src/layers/batch_norm_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/batch_norm_layer.cpp.i
.PHONY : src/layers/batch_norm_layer.cpp.i

src/layers/batch_norm_layer.s: src/layers/batch_norm_layer.cpp.s

.PHONY : src/layers/batch_norm_layer.s

# target to generate assembly for a file
src/layers/batch_norm_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/batch_norm_layer.cpp.s
.PHONY : src/layers/batch_norm_layer.cpp.s

src/layers/bias_layer.o: src/layers/bias_layer.cpp.o

.PHONY : src/layers/bias_layer.o

# target to build an object file
src/layers/bias_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bias_layer.cpp.o
.PHONY : src/layers/bias_layer.cpp.o

src/layers/bias_layer.i: src/layers/bias_layer.cpp.i

.PHONY : src/layers/bias_layer.i

# target to preprocess a source file
src/layers/bias_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bias_layer.cpp.i
.PHONY : src/layers/bias_layer.cpp.i

src/layers/bias_layer.s: src/layers/bias_layer.cpp.s

.PHONY : src/layers/bias_layer.s

# target to generate assembly for a file
src/layers/bias_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bias_layer.cpp.s
.PHONY : src/layers/bias_layer.cpp.s

src/layers/bn_layer.o: src/layers/bn_layer.cpp.o

.PHONY : src/layers/bn_layer.o

# target to build an object file
src/layers/bn_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bn_layer.cpp.o
.PHONY : src/layers/bn_layer.cpp.o

src/layers/bn_layer.i: src/layers/bn_layer.cpp.i

.PHONY : src/layers/bn_layer.i

# target to preprocess a source file
src/layers/bn_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bn_layer.cpp.i
.PHONY : src/layers/bn_layer.cpp.i

src/layers/bn_layer.s: src/layers/bn_layer.cpp.s

.PHONY : src/layers/bn_layer.s

# target to generate assembly for a file
src/layers/bn_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bn_layer.cpp.s
.PHONY : src/layers/bn_layer.cpp.s

src/layers/bnll_layer.o: src/layers/bnll_layer.cpp.o

.PHONY : src/layers/bnll_layer.o

# target to build an object file
src/layers/bnll_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bnll_layer.cpp.o
.PHONY : src/layers/bnll_layer.cpp.o

src/layers/bnll_layer.i: src/layers/bnll_layer.cpp.i

.PHONY : src/layers/bnll_layer.i

# target to preprocess a source file
src/layers/bnll_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bnll_layer.cpp.i
.PHONY : src/layers/bnll_layer.cpp.i

src/layers/bnll_layer.s: src/layers/bnll_layer.cpp.s

.PHONY : src/layers/bnll_layer.s

# target to generate assembly for a file
src/layers/bnll_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/bnll_layer.cpp.s
.PHONY : src/layers/bnll_layer.cpp.s

src/layers/concat_layer.o: src/layers/concat_layer.cpp.o

.PHONY : src/layers/concat_layer.o

# target to build an object file
src/layers/concat_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/concat_layer.cpp.o
.PHONY : src/layers/concat_layer.cpp.o

src/layers/concat_layer.i: src/layers/concat_layer.cpp.i

.PHONY : src/layers/concat_layer.i

# target to preprocess a source file
src/layers/concat_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/concat_layer.cpp.i
.PHONY : src/layers/concat_layer.cpp.i

src/layers/concat_layer.s: src/layers/concat_layer.cpp.s

.PHONY : src/layers/concat_layer.s

# target to generate assembly for a file
src/layers/concat_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/concat_layer.cpp.s
.PHONY : src/layers/concat_layer.cpp.s

src/layers/conv_dw_layer.o: src/layers/conv_dw_layer.cpp.o

.PHONY : src/layers/conv_dw_layer.o

# target to build an object file
src/layers/conv_dw_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_dw_layer.cpp.o
.PHONY : src/layers/conv_dw_layer.cpp.o

src/layers/conv_dw_layer.i: src/layers/conv_dw_layer.cpp.i

.PHONY : src/layers/conv_dw_layer.i

# target to preprocess a source file
src/layers/conv_dw_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_dw_layer.cpp.i
.PHONY : src/layers/conv_dw_layer.cpp.i

src/layers/conv_dw_layer.s: src/layers/conv_dw_layer.cpp.s

.PHONY : src/layers/conv_dw_layer.s

# target to generate assembly for a file
src/layers/conv_dw_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_dw_layer.cpp.s
.PHONY : src/layers/conv_dw_layer.cpp.s

src/layers/conv_layer.o: src/layers/conv_layer.cpp.o

.PHONY : src/layers/conv_layer.o

# target to build an object file
src/layers/conv_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_layer.cpp.o
.PHONY : src/layers/conv_layer.cpp.o

src/layers/conv_layer.i: src/layers/conv_layer.cpp.i

.PHONY : src/layers/conv_layer.i

# target to preprocess a source file
src/layers/conv_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_layer.cpp.i
.PHONY : src/layers/conv_layer.cpp.i

src/layers/conv_layer.s: src/layers/conv_layer.cpp.s

.PHONY : src/layers/conv_layer.s

# target to generate assembly for a file
src/layers/conv_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/conv_layer.cpp.s
.PHONY : src/layers/conv_layer.cpp.s

src/layers/crop_layer.o: src/layers/crop_layer.cpp.o

.PHONY : src/layers/crop_layer.o

# target to build an object file
src/layers/crop_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/crop_layer.cpp.o
.PHONY : src/layers/crop_layer.cpp.o

src/layers/crop_layer.i: src/layers/crop_layer.cpp.i

.PHONY : src/layers/crop_layer.i

# target to preprocess a source file
src/layers/crop_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/crop_layer.cpp.i
.PHONY : src/layers/crop_layer.cpp.i

src/layers/crop_layer.s: src/layers/crop_layer.cpp.s

.PHONY : src/layers/crop_layer.s

# target to generate assembly for a file
src/layers/crop_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/crop_layer.cpp.s
.PHONY : src/layers/crop_layer.cpp.s

src/layers/deconv_layer.o: src/layers/deconv_layer.cpp.o

.PHONY : src/layers/deconv_layer.o

# target to build an object file
src/layers/deconv_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/deconv_layer.cpp.o
.PHONY : src/layers/deconv_layer.cpp.o

src/layers/deconv_layer.i: src/layers/deconv_layer.cpp.i

.PHONY : src/layers/deconv_layer.i

# target to preprocess a source file
src/layers/deconv_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/deconv_layer.cpp.i
.PHONY : src/layers/deconv_layer.cpp.i

src/layers/deconv_layer.s: src/layers/deconv_layer.cpp.s

.PHONY : src/layers/deconv_layer.s

# target to generate assembly for a file
src/layers/deconv_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/deconv_layer.cpp.s
.PHONY : src/layers/deconv_layer.cpp.s

src/layers/detection_output_layer.o: src/layers/detection_output_layer.cpp.o

.PHONY : src/layers/detection_output_layer.o

# target to build an object file
src/layers/detection_output_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/detection_output_layer.cpp.o
.PHONY : src/layers/detection_output_layer.cpp.o

src/layers/detection_output_layer.i: src/layers/detection_output_layer.cpp.i

.PHONY : src/layers/detection_output_layer.i

# target to preprocess a source file
src/layers/detection_output_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/detection_output_layer.cpp.i
.PHONY : src/layers/detection_output_layer.cpp.i

src/layers/detection_output_layer.s: src/layers/detection_output_layer.cpp.s

.PHONY : src/layers/detection_output_layer.s

# target to generate assembly for a file
src/layers/detection_output_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/detection_output_layer.cpp.s
.PHONY : src/layers/detection_output_layer.cpp.s

src/layers/dropout_layer.o: src/layers/dropout_layer.cpp.o

.PHONY : src/layers/dropout_layer.o

# target to build an object file
src/layers/dropout_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/dropout_layer.cpp.o
.PHONY : src/layers/dropout_layer.cpp.o

src/layers/dropout_layer.i: src/layers/dropout_layer.cpp.i

.PHONY : src/layers/dropout_layer.i

# target to preprocess a source file
src/layers/dropout_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/dropout_layer.cpp.i
.PHONY : src/layers/dropout_layer.cpp.i

src/layers/dropout_layer.s: src/layers/dropout_layer.cpp.s

.PHONY : src/layers/dropout_layer.s

# target to generate assembly for a file
src/layers/dropout_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/dropout_layer.cpp.s
.PHONY : src/layers/dropout_layer.cpp.s

src/layers/eltwise_layer.o: src/layers/eltwise_layer.cpp.o

.PHONY : src/layers/eltwise_layer.o

# target to build an object file
src/layers/eltwise_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/eltwise_layer.cpp.o
.PHONY : src/layers/eltwise_layer.cpp.o

src/layers/eltwise_layer.i: src/layers/eltwise_layer.cpp.i

.PHONY : src/layers/eltwise_layer.i

# target to preprocess a source file
src/layers/eltwise_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/eltwise_layer.cpp.i
.PHONY : src/layers/eltwise_layer.cpp.i

src/layers/eltwise_layer.s: src/layers/eltwise_layer.cpp.s

.PHONY : src/layers/eltwise_layer.s

# target to generate assembly for a file
src/layers/eltwise_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/eltwise_layer.cpp.s
.PHONY : src/layers/eltwise_layer.cpp.s

src/layers/elu_layer.o: src/layers/elu_layer.cpp.o

.PHONY : src/layers/elu_layer.o

# target to build an object file
src/layers/elu_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/elu_layer.cpp.o
.PHONY : src/layers/elu_layer.cpp.o

src/layers/elu_layer.i: src/layers/elu_layer.cpp.i

.PHONY : src/layers/elu_layer.i

# target to preprocess a source file
src/layers/elu_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/elu_layer.cpp.i
.PHONY : src/layers/elu_layer.cpp.i

src/layers/elu_layer.s: src/layers/elu_layer.cpp.s

.PHONY : src/layers/elu_layer.s

# target to generate assembly for a file
src/layers/elu_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/elu_layer.cpp.s
.PHONY : src/layers/elu_layer.cpp.s

src/layers/embed_layer.o: src/layers/embed_layer.cpp.o

.PHONY : src/layers/embed_layer.o

# target to build an object file
src/layers/embed_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/embed_layer.cpp.o
.PHONY : src/layers/embed_layer.cpp.o

src/layers/embed_layer.i: src/layers/embed_layer.cpp.i

.PHONY : src/layers/embed_layer.i

# target to preprocess a source file
src/layers/embed_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/embed_layer.cpp.i
.PHONY : src/layers/embed_layer.cpp.i

src/layers/embed_layer.s: src/layers/embed_layer.cpp.s

.PHONY : src/layers/embed_layer.s

# target to generate assembly for a file
src/layers/embed_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/embed_layer.cpp.s
.PHONY : src/layers/embed_layer.cpp.s

src/layers/exp_layer.o: src/layers/exp_layer.cpp.o

.PHONY : src/layers/exp_layer.o

# target to build an object file
src/layers/exp_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/exp_layer.cpp.o
.PHONY : src/layers/exp_layer.cpp.o

src/layers/exp_layer.i: src/layers/exp_layer.cpp.i

.PHONY : src/layers/exp_layer.i

# target to preprocess a source file
src/layers/exp_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/exp_layer.cpp.i
.PHONY : src/layers/exp_layer.cpp.i

src/layers/exp_layer.s: src/layers/exp_layer.cpp.s

.PHONY : src/layers/exp_layer.s

# target to generate assembly for a file
src/layers/exp_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/exp_layer.cpp.s
.PHONY : src/layers/exp_layer.cpp.s

src/layers/filter_layer.o: src/layers/filter_layer.cpp.o

.PHONY : src/layers/filter_layer.o

# target to build an object file
src/layers/filter_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/filter_layer.cpp.o
.PHONY : src/layers/filter_layer.cpp.o

src/layers/filter_layer.i: src/layers/filter_layer.cpp.i

.PHONY : src/layers/filter_layer.i

# target to preprocess a source file
src/layers/filter_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/filter_layer.cpp.i
.PHONY : src/layers/filter_layer.cpp.i

src/layers/filter_layer.s: src/layers/filter_layer.cpp.s

.PHONY : src/layers/filter_layer.s

# target to generate assembly for a file
src/layers/filter_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/filter_layer.cpp.s
.PHONY : src/layers/filter_layer.cpp.s

src/layers/flatten_layer.o: src/layers/flatten_layer.cpp.o

.PHONY : src/layers/flatten_layer.o

# target to build an object file
src/layers/flatten_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/flatten_layer.cpp.o
.PHONY : src/layers/flatten_layer.cpp.o

src/layers/flatten_layer.i: src/layers/flatten_layer.cpp.i

.PHONY : src/layers/flatten_layer.i

# target to preprocess a source file
src/layers/flatten_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/flatten_layer.cpp.i
.PHONY : src/layers/flatten_layer.cpp.i

src/layers/flatten_layer.s: src/layers/flatten_layer.cpp.s

.PHONY : src/layers/flatten_layer.s

# target to generate assembly for a file
src/layers/flatten_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/flatten_layer.cpp.s
.PHONY : src/layers/flatten_layer.cpp.s

src/layers/inner_product_layer.o: src/layers/inner_product_layer.cpp.o

.PHONY : src/layers/inner_product_layer.o

# target to build an object file
src/layers/inner_product_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/inner_product_layer.cpp.o
.PHONY : src/layers/inner_product_layer.cpp.o

src/layers/inner_product_layer.i: src/layers/inner_product_layer.cpp.i

.PHONY : src/layers/inner_product_layer.i

# target to preprocess a source file
src/layers/inner_product_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/inner_product_layer.cpp.i
.PHONY : src/layers/inner_product_layer.cpp.i

src/layers/inner_product_layer.s: src/layers/inner_product_layer.cpp.s

.PHONY : src/layers/inner_product_layer.s

# target to generate assembly for a file
src/layers/inner_product_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/inner_product_layer.cpp.s
.PHONY : src/layers/inner_product_layer.cpp.s

src/layers/input_layer.o: src/layers/input_layer.cpp.o

.PHONY : src/layers/input_layer.o

# target to build an object file
src/layers/input_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/input_layer.cpp.o
.PHONY : src/layers/input_layer.cpp.o

src/layers/input_layer.i: src/layers/input_layer.cpp.i

.PHONY : src/layers/input_layer.i

# target to preprocess a source file
src/layers/input_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/input_layer.cpp.i
.PHONY : src/layers/input_layer.cpp.i

src/layers/input_layer.s: src/layers/input_layer.cpp.s

.PHONY : src/layers/input_layer.s

# target to generate assembly for a file
src/layers/input_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/input_layer.cpp.s
.PHONY : src/layers/input_layer.cpp.s

src/layers/log_layer.o: src/layers/log_layer.cpp.o

.PHONY : src/layers/log_layer.o

# target to build an object file
src/layers/log_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/log_layer.cpp.o
.PHONY : src/layers/log_layer.cpp.o

src/layers/log_layer.i: src/layers/log_layer.cpp.i

.PHONY : src/layers/log_layer.i

# target to preprocess a source file
src/layers/log_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/log_layer.cpp.i
.PHONY : src/layers/log_layer.cpp.i

src/layers/log_layer.s: src/layers/log_layer.cpp.s

.PHONY : src/layers/log_layer.s

# target to generate assembly for a file
src/layers/log_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/log_layer.cpp.s
.PHONY : src/layers/log_layer.cpp.s

src/layers/lrn_layer.o: src/layers/lrn_layer.cpp.o

.PHONY : src/layers/lrn_layer.o

# target to build an object file
src/layers/lrn_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/lrn_layer.cpp.o
.PHONY : src/layers/lrn_layer.cpp.o

src/layers/lrn_layer.i: src/layers/lrn_layer.cpp.i

.PHONY : src/layers/lrn_layer.i

# target to preprocess a source file
src/layers/lrn_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/lrn_layer.cpp.i
.PHONY : src/layers/lrn_layer.cpp.i

src/layers/lrn_layer.s: src/layers/lrn_layer.cpp.s

.PHONY : src/layers/lrn_layer.s

# target to generate assembly for a file
src/layers/lrn_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/lrn_layer.cpp.s
.PHONY : src/layers/lrn_layer.cpp.s

src/layers/mvn_layer.o: src/layers/mvn_layer.cpp.o

.PHONY : src/layers/mvn_layer.o

# target to build an object file
src/layers/mvn_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/mvn_layer.cpp.o
.PHONY : src/layers/mvn_layer.cpp.o

src/layers/mvn_layer.i: src/layers/mvn_layer.cpp.i

.PHONY : src/layers/mvn_layer.i

# target to preprocess a source file
src/layers/mvn_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/mvn_layer.cpp.i
.PHONY : src/layers/mvn_layer.cpp.i

src/layers/mvn_layer.s: src/layers/mvn_layer.cpp.s

.PHONY : src/layers/mvn_layer.s

# target to generate assembly for a file
src/layers/mvn_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/mvn_layer.cpp.s
.PHONY : src/layers/mvn_layer.cpp.s

src/layers/neuron_layer.o: src/layers/neuron_layer.cpp.o

.PHONY : src/layers/neuron_layer.o

# target to build an object file
src/layers/neuron_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/neuron_layer.cpp.o
.PHONY : src/layers/neuron_layer.cpp.o

src/layers/neuron_layer.i: src/layers/neuron_layer.cpp.i

.PHONY : src/layers/neuron_layer.i

# target to preprocess a source file
src/layers/neuron_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/neuron_layer.cpp.i
.PHONY : src/layers/neuron_layer.cpp.i

src/layers/neuron_layer.s: src/layers/neuron_layer.cpp.s

.PHONY : src/layers/neuron_layer.s

# target to generate assembly for a file
src/layers/neuron_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/neuron_layer.cpp.s
.PHONY : src/layers/neuron_layer.cpp.s

src/layers/normalize_layer.o: src/layers/normalize_layer.cpp.o

.PHONY : src/layers/normalize_layer.o

# target to build an object file
src/layers/normalize_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/normalize_layer.cpp.o
.PHONY : src/layers/normalize_layer.cpp.o

src/layers/normalize_layer.i: src/layers/normalize_layer.cpp.i

.PHONY : src/layers/normalize_layer.i

# target to preprocess a source file
src/layers/normalize_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/normalize_layer.cpp.i
.PHONY : src/layers/normalize_layer.cpp.i

src/layers/normalize_layer.s: src/layers/normalize_layer.cpp.s

.PHONY : src/layers/normalize_layer.s

# target to generate assembly for a file
src/layers/normalize_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/normalize_layer.cpp.s
.PHONY : src/layers/normalize_layer.cpp.s

src/layers/parameter_layer.o: src/layers/parameter_layer.cpp.o

.PHONY : src/layers/parameter_layer.o

# target to build an object file
src/layers/parameter_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/parameter_layer.cpp.o
.PHONY : src/layers/parameter_layer.cpp.o

src/layers/parameter_layer.i: src/layers/parameter_layer.cpp.i

.PHONY : src/layers/parameter_layer.i

# target to preprocess a source file
src/layers/parameter_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/parameter_layer.cpp.i
.PHONY : src/layers/parameter_layer.cpp.i

src/layers/parameter_layer.s: src/layers/parameter_layer.cpp.s

.PHONY : src/layers/parameter_layer.s

# target to generate assembly for a file
src/layers/parameter_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/parameter_layer.cpp.s
.PHONY : src/layers/parameter_layer.cpp.s

src/layers/permute_layer.o: src/layers/permute_layer.cpp.o

.PHONY : src/layers/permute_layer.o

# target to build an object file
src/layers/permute_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/permute_layer.cpp.o
.PHONY : src/layers/permute_layer.cpp.o

src/layers/permute_layer.i: src/layers/permute_layer.cpp.i

.PHONY : src/layers/permute_layer.i

# target to preprocess a source file
src/layers/permute_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/permute_layer.cpp.i
.PHONY : src/layers/permute_layer.cpp.i

src/layers/permute_layer.s: src/layers/permute_layer.cpp.s

.PHONY : src/layers/permute_layer.s

# target to generate assembly for a file
src/layers/permute_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/permute_layer.cpp.s
.PHONY : src/layers/permute_layer.cpp.s

src/layers/pooling_layer.o: src/layers/pooling_layer.cpp.o

.PHONY : src/layers/pooling_layer.o

# target to build an object file
src/layers/pooling_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/pooling_layer.cpp.o
.PHONY : src/layers/pooling_layer.cpp.o

src/layers/pooling_layer.i: src/layers/pooling_layer.cpp.i

.PHONY : src/layers/pooling_layer.i

# target to preprocess a source file
src/layers/pooling_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/pooling_layer.cpp.i
.PHONY : src/layers/pooling_layer.cpp.i

src/layers/pooling_layer.s: src/layers/pooling_layer.cpp.s

.PHONY : src/layers/pooling_layer.s

# target to generate assembly for a file
src/layers/pooling_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/pooling_layer.cpp.s
.PHONY : src/layers/pooling_layer.cpp.s

src/layers/power_layer.o: src/layers/power_layer.cpp.o

.PHONY : src/layers/power_layer.o

# target to build an object file
src/layers/power_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/power_layer.cpp.o
.PHONY : src/layers/power_layer.cpp.o

src/layers/power_layer.i: src/layers/power_layer.cpp.i

.PHONY : src/layers/power_layer.i

# target to preprocess a source file
src/layers/power_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/power_layer.cpp.i
.PHONY : src/layers/power_layer.cpp.i

src/layers/power_layer.s: src/layers/power_layer.cpp.s

.PHONY : src/layers/power_layer.s

# target to generate assembly for a file
src/layers/power_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/power_layer.cpp.s
.PHONY : src/layers/power_layer.cpp.s

src/layers/prelu_layer.o: src/layers/prelu_layer.cpp.o

.PHONY : src/layers/prelu_layer.o

# target to build an object file
src/layers/prelu_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prelu_layer.cpp.o
.PHONY : src/layers/prelu_layer.cpp.o

src/layers/prelu_layer.i: src/layers/prelu_layer.cpp.i

.PHONY : src/layers/prelu_layer.i

# target to preprocess a source file
src/layers/prelu_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prelu_layer.cpp.i
.PHONY : src/layers/prelu_layer.cpp.i

src/layers/prelu_layer.s: src/layers/prelu_layer.cpp.s

.PHONY : src/layers/prelu_layer.s

# target to generate assembly for a file
src/layers/prelu_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prelu_layer.cpp.s
.PHONY : src/layers/prelu_layer.cpp.s

src/layers/prior_box_layer.o: src/layers/prior_box_layer.cpp.o

.PHONY : src/layers/prior_box_layer.o

# target to build an object file
src/layers/prior_box_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prior_box_layer.cpp.o
.PHONY : src/layers/prior_box_layer.cpp.o

src/layers/prior_box_layer.i: src/layers/prior_box_layer.cpp.i

.PHONY : src/layers/prior_box_layer.i

# target to preprocess a source file
src/layers/prior_box_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prior_box_layer.cpp.i
.PHONY : src/layers/prior_box_layer.cpp.i

src/layers/prior_box_layer.s: src/layers/prior_box_layer.cpp.s

.PHONY : src/layers/prior_box_layer.s

# target to generate assembly for a file
src/layers/prior_box_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/prior_box_layer.cpp.s
.PHONY : src/layers/prior_box_layer.cpp.s

src/layers/proposal_layer.o: src/layers/proposal_layer.cpp.o

.PHONY : src/layers/proposal_layer.o

# target to build an object file
src/layers/proposal_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/proposal_layer.cpp.o
.PHONY : src/layers/proposal_layer.cpp.o

src/layers/proposal_layer.i: src/layers/proposal_layer.cpp.i

.PHONY : src/layers/proposal_layer.i

# target to preprocess a source file
src/layers/proposal_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/proposal_layer.cpp.i
.PHONY : src/layers/proposal_layer.cpp.i

src/layers/proposal_layer.s: src/layers/proposal_layer.cpp.s

.PHONY : src/layers/proposal_layer.s

# target to generate assembly for a file
src/layers/proposal_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/proposal_layer.cpp.s
.PHONY : src/layers/proposal_layer.cpp.s

src/layers/psroi_pooling_layer.o: src/layers/psroi_pooling_layer.cpp.o

.PHONY : src/layers/psroi_pooling_layer.o

# target to build an object file
src/layers/psroi_pooling_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/psroi_pooling_layer.cpp.o
.PHONY : src/layers/psroi_pooling_layer.cpp.o

src/layers/psroi_pooling_layer.i: src/layers/psroi_pooling_layer.cpp.i

.PHONY : src/layers/psroi_pooling_layer.i

# target to preprocess a source file
src/layers/psroi_pooling_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/psroi_pooling_layer.cpp.i
.PHONY : src/layers/psroi_pooling_layer.cpp.i

src/layers/psroi_pooling_layer.s: src/layers/psroi_pooling_layer.cpp.s

.PHONY : src/layers/psroi_pooling_layer.s

# target to generate assembly for a file
src/layers/psroi_pooling_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/psroi_pooling_layer.cpp.s
.PHONY : src/layers/psroi_pooling_layer.cpp.s

src/layers/reduction_layer.o: src/layers/reduction_layer.cpp.o

.PHONY : src/layers/reduction_layer.o

# target to build an object file
src/layers/reduction_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reduction_layer.cpp.o
.PHONY : src/layers/reduction_layer.cpp.o

src/layers/reduction_layer.i: src/layers/reduction_layer.cpp.i

.PHONY : src/layers/reduction_layer.i

# target to preprocess a source file
src/layers/reduction_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reduction_layer.cpp.i
.PHONY : src/layers/reduction_layer.cpp.i

src/layers/reduction_layer.s: src/layers/reduction_layer.cpp.s

.PHONY : src/layers/reduction_layer.s

# target to generate assembly for a file
src/layers/reduction_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reduction_layer.cpp.s
.PHONY : src/layers/reduction_layer.cpp.s

src/layers/relu_layer.o: src/layers/relu_layer.cpp.o

.PHONY : src/layers/relu_layer.o

# target to build an object file
src/layers/relu_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/relu_layer.cpp.o
.PHONY : src/layers/relu_layer.cpp.o

src/layers/relu_layer.i: src/layers/relu_layer.cpp.i

.PHONY : src/layers/relu_layer.i

# target to preprocess a source file
src/layers/relu_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/relu_layer.cpp.i
.PHONY : src/layers/relu_layer.cpp.i

src/layers/relu_layer.s: src/layers/relu_layer.cpp.s

.PHONY : src/layers/relu_layer.s

# target to generate assembly for a file
src/layers/relu_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/relu_layer.cpp.s
.PHONY : src/layers/relu_layer.cpp.s

src/layers/reshape_layer.o: src/layers/reshape_layer.cpp.o

.PHONY : src/layers/reshape_layer.o

# target to build an object file
src/layers/reshape_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reshape_layer.cpp.o
.PHONY : src/layers/reshape_layer.cpp.o

src/layers/reshape_layer.i: src/layers/reshape_layer.cpp.i

.PHONY : src/layers/reshape_layer.i

# target to preprocess a source file
src/layers/reshape_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reshape_layer.cpp.i
.PHONY : src/layers/reshape_layer.cpp.i

src/layers/reshape_layer.s: src/layers/reshape_layer.cpp.s

.PHONY : src/layers/reshape_layer.s

# target to generate assembly for a file
src/layers/reshape_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/reshape_layer.cpp.s
.PHONY : src/layers/reshape_layer.cpp.s

src/layers/roi_pooling_layer.o: src/layers/roi_pooling_layer.cpp.o

.PHONY : src/layers/roi_pooling_layer.o

# target to build an object file
src/layers/roi_pooling_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/roi_pooling_layer.cpp.o
.PHONY : src/layers/roi_pooling_layer.cpp.o

src/layers/roi_pooling_layer.i: src/layers/roi_pooling_layer.cpp.i

.PHONY : src/layers/roi_pooling_layer.i

# target to preprocess a source file
src/layers/roi_pooling_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/roi_pooling_layer.cpp.i
.PHONY : src/layers/roi_pooling_layer.cpp.i

src/layers/roi_pooling_layer.s: src/layers/roi_pooling_layer.cpp.s

.PHONY : src/layers/roi_pooling_layer.s

# target to generate assembly for a file
src/layers/roi_pooling_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/roi_pooling_layer.cpp.s
.PHONY : src/layers/roi_pooling_layer.cpp.s

src/layers/scale_layer.o: src/layers/scale_layer.cpp.o

.PHONY : src/layers/scale_layer.o

# target to build an object file
src/layers/scale_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/scale_layer.cpp.o
.PHONY : src/layers/scale_layer.cpp.o

src/layers/scale_layer.i: src/layers/scale_layer.cpp.i

.PHONY : src/layers/scale_layer.i

# target to preprocess a source file
src/layers/scale_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/scale_layer.cpp.i
.PHONY : src/layers/scale_layer.cpp.i

src/layers/scale_layer.s: src/layers/scale_layer.cpp.s

.PHONY : src/layers/scale_layer.s

# target to generate assembly for a file
src/layers/scale_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/scale_layer.cpp.s
.PHONY : src/layers/scale_layer.cpp.s

src/layers/shuffle_channel_layer.o: src/layers/shuffle_channel_layer.cpp.o

.PHONY : src/layers/shuffle_channel_layer.o

# target to build an object file
src/layers/shuffle_channel_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/shuffle_channel_layer.cpp.o
.PHONY : src/layers/shuffle_channel_layer.cpp.o

src/layers/shuffle_channel_layer.i: src/layers/shuffle_channel_layer.cpp.i

.PHONY : src/layers/shuffle_channel_layer.i

# target to preprocess a source file
src/layers/shuffle_channel_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/shuffle_channel_layer.cpp.i
.PHONY : src/layers/shuffle_channel_layer.cpp.i

src/layers/shuffle_channel_layer.s: src/layers/shuffle_channel_layer.cpp.s

.PHONY : src/layers/shuffle_channel_layer.s

# target to generate assembly for a file
src/layers/shuffle_channel_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/shuffle_channel_layer.cpp.s
.PHONY : src/layers/shuffle_channel_layer.cpp.s

src/layers/sigmoid_layer.o: src/layers/sigmoid_layer.cpp.o

.PHONY : src/layers/sigmoid_layer.o

# target to build an object file
src/layers/sigmoid_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/sigmoid_layer.cpp.o
.PHONY : src/layers/sigmoid_layer.cpp.o

src/layers/sigmoid_layer.i: src/layers/sigmoid_layer.cpp.i

.PHONY : src/layers/sigmoid_layer.i

# target to preprocess a source file
src/layers/sigmoid_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/sigmoid_layer.cpp.i
.PHONY : src/layers/sigmoid_layer.cpp.i

src/layers/sigmoid_layer.s: src/layers/sigmoid_layer.cpp.s

.PHONY : src/layers/sigmoid_layer.s

# target to generate assembly for a file
src/layers/sigmoid_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/sigmoid_layer.cpp.s
.PHONY : src/layers/sigmoid_layer.cpp.s

src/layers/slice_layer.o: src/layers/slice_layer.cpp.o

.PHONY : src/layers/slice_layer.o

# target to build an object file
src/layers/slice_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/slice_layer.cpp.o
.PHONY : src/layers/slice_layer.cpp.o

src/layers/slice_layer.i: src/layers/slice_layer.cpp.i

.PHONY : src/layers/slice_layer.i

# target to preprocess a source file
src/layers/slice_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/slice_layer.cpp.i
.PHONY : src/layers/slice_layer.cpp.i

src/layers/slice_layer.s: src/layers/slice_layer.cpp.s

.PHONY : src/layers/slice_layer.s

# target to generate assembly for a file
src/layers/slice_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/slice_layer.cpp.s
.PHONY : src/layers/slice_layer.cpp.s

src/layers/softmax_layer.o: src/layers/softmax_layer.cpp.o

.PHONY : src/layers/softmax_layer.o

# target to build an object file
src/layers/softmax_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/softmax_layer.cpp.o
.PHONY : src/layers/softmax_layer.cpp.o

src/layers/softmax_layer.i: src/layers/softmax_layer.cpp.i

.PHONY : src/layers/softmax_layer.i

# target to preprocess a source file
src/layers/softmax_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/softmax_layer.cpp.i
.PHONY : src/layers/softmax_layer.cpp.i

src/layers/softmax_layer.s: src/layers/softmax_layer.cpp.s

.PHONY : src/layers/softmax_layer.s

# target to generate assembly for a file
src/layers/softmax_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/softmax_layer.cpp.s
.PHONY : src/layers/softmax_layer.cpp.s

src/layers/split_layer.o: src/layers/split_layer.cpp.o

.PHONY : src/layers/split_layer.o

# target to build an object file
src/layers/split_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/split_layer.cpp.o
.PHONY : src/layers/split_layer.cpp.o

src/layers/split_layer.i: src/layers/split_layer.cpp.i

.PHONY : src/layers/split_layer.i

# target to preprocess a source file
src/layers/split_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/split_layer.cpp.i
.PHONY : src/layers/split_layer.cpp.i

src/layers/split_layer.s: src/layers/split_layer.cpp.s

.PHONY : src/layers/split_layer.s

# target to generate assembly for a file
src/layers/split_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/split_layer.cpp.s
.PHONY : src/layers/split_layer.cpp.s

src/layers/spp_layer.o: src/layers/spp_layer.cpp.o

.PHONY : src/layers/spp_layer.o

# target to build an object file
src/layers/spp_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/spp_layer.cpp.o
.PHONY : src/layers/spp_layer.cpp.o

src/layers/spp_layer.i: src/layers/spp_layer.cpp.i

.PHONY : src/layers/spp_layer.i

# target to preprocess a source file
src/layers/spp_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/spp_layer.cpp.i
.PHONY : src/layers/spp_layer.cpp.i

src/layers/spp_layer.s: src/layers/spp_layer.cpp.s

.PHONY : src/layers/spp_layer.s

# target to generate assembly for a file
src/layers/spp_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/spp_layer.cpp.s
.PHONY : src/layers/spp_layer.cpp.s

src/layers/tanh_layer.o: src/layers/tanh_layer.cpp.o

.PHONY : src/layers/tanh_layer.o

# target to build an object file
src/layers/tanh_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tanh_layer.cpp.o
.PHONY : src/layers/tanh_layer.cpp.o

src/layers/tanh_layer.i: src/layers/tanh_layer.cpp.i

.PHONY : src/layers/tanh_layer.i

# target to preprocess a source file
src/layers/tanh_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tanh_layer.cpp.i
.PHONY : src/layers/tanh_layer.cpp.i

src/layers/tanh_layer.s: src/layers/tanh_layer.cpp.s

.PHONY : src/layers/tanh_layer.s

# target to generate assembly for a file
src/layers/tanh_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tanh_layer.cpp.s
.PHONY : src/layers/tanh_layer.cpp.s

src/layers/threshold_layer.o: src/layers/threshold_layer.cpp.o

.PHONY : src/layers/threshold_layer.o

# target to build an object file
src/layers/threshold_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/threshold_layer.cpp.o
.PHONY : src/layers/threshold_layer.cpp.o

src/layers/threshold_layer.i: src/layers/threshold_layer.cpp.i

.PHONY : src/layers/threshold_layer.i

# target to preprocess a source file
src/layers/threshold_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/threshold_layer.cpp.i
.PHONY : src/layers/threshold_layer.cpp.i

src/layers/threshold_layer.s: src/layers/threshold_layer.cpp.s

.PHONY : src/layers/threshold_layer.s

# target to generate assembly for a file
src/layers/threshold_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/threshold_layer.cpp.s
.PHONY : src/layers/threshold_layer.cpp.s

src/layers/tile_layer.o: src/layers/tile_layer.cpp.o

.PHONY : src/layers/tile_layer.o

# target to build an object file
src/layers/tile_layer.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tile_layer.cpp.o
.PHONY : src/layers/tile_layer.cpp.o

src/layers/tile_layer.i: src/layers/tile_layer.cpp.i

.PHONY : src/layers/tile_layer.i

# target to preprocess a source file
src/layers/tile_layer.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tile_layer.cpp.i
.PHONY : src/layers/tile_layer.cpp.i

src/layers/tile_layer.s: src/layers/tile_layer.cpp.s

.PHONY : src/layers/tile_layer.s

# target to generate assembly for a file
src/layers/tile_layer.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/layers/tile_layer.cpp.s
.PHONY : src/layers/tile_layer.cpp.s

src/net.o: src/net.cpp.o

.PHONY : src/net.o

# target to build an object file
src/net.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/net.cpp.o
.PHONY : src/net.cpp.o

src/net.i: src/net.cpp.i

.PHONY : src/net.i

# target to preprocess a source file
src/net.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/net.cpp.i
.PHONY : src/net.cpp.i

src/net.s: src/net.cpp.s

.PHONY : src/net.s

# target to generate assembly for a file
src/net.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/net.cpp.s
.PHONY : src/net.cpp.s

src/profiler.o: src/profiler.cpp.o

.PHONY : src/profiler.o

# target to build an object file
src/profiler.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/profiler.cpp.o
.PHONY : src/profiler.cpp.o

src/profiler.i: src/profiler.cpp.i

.PHONY : src/profiler.i

# target to preprocess a source file
src/profiler.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/profiler.cpp.i
.PHONY : src/profiler.cpp.i

src/profiler.s: src/profiler.cpp.s

.PHONY : src/profiler.s

# target to generate assembly for a file
src/profiler.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/profiler.cpp.s
.PHONY : src/profiler.cpp.s

src/proto/caffe.pb.o: src/proto/caffe.pb.cc.o

.PHONY : src/proto/caffe.pb.o

# target to build an object file
src/proto/caffe.pb.cc.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/proto/caffe.pb.cc.o
.PHONY : src/proto/caffe.pb.cc.o

src/proto/caffe.pb.i: src/proto/caffe.pb.cc.i

.PHONY : src/proto/caffe.pb.i

# target to preprocess a source file
src/proto/caffe.pb.cc.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/proto/caffe.pb.cc.i
.PHONY : src/proto/caffe.pb.cc.i

src/proto/caffe.pb.s: src/proto/caffe.pb.cc.s

.PHONY : src/proto/caffe.pb.s

# target to generate assembly for a file
src/proto/caffe.pb.cc.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/proto/caffe.pb.cc.s
.PHONY : src/proto/caffe.pb.cc.s

src/syncedmem.o: src/syncedmem.cpp.o

.PHONY : src/syncedmem.o

# target to build an object file
src/syncedmem.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/syncedmem.cpp.o
.PHONY : src/syncedmem.cpp.o

src/syncedmem.i: src/syncedmem.cpp.i

.PHONY : src/syncedmem.i

# target to preprocess a source file
src/syncedmem.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/syncedmem.cpp.i
.PHONY : src/syncedmem.cpp.i

src/syncedmem.s: src/syncedmem.cpp.s

.PHONY : src/syncedmem.s

# target to generate assembly for a file
src/syncedmem.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/syncedmem.cpp.s
.PHONY : src/syncedmem.cpp.s

src/util/bbox_util.o: src/util/bbox_util.cpp.o

.PHONY : src/util/bbox_util.o

# target to build an object file
src/util/bbox_util.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/bbox_util.cpp.o
.PHONY : src/util/bbox_util.cpp.o

src/util/bbox_util.i: src/util/bbox_util.cpp.i

.PHONY : src/util/bbox_util.i

# target to preprocess a source file
src/util/bbox_util.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/bbox_util.cpp.i
.PHONY : src/util/bbox_util.cpp.i

src/util/bbox_util.s: src/util/bbox_util.cpp.s

.PHONY : src/util/bbox_util.s

# target to generate assembly for a file
src/util/bbox_util.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/bbox_util.cpp.s
.PHONY : src/util/bbox_util.cpp.s

src/util/im2col.o: src/util/im2col.cpp.o

.PHONY : src/util/im2col.o

# target to build an object file
src/util/im2col.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/im2col.cpp.o
.PHONY : src/util/im2col.cpp.o

src/util/im2col.i: src/util/im2col.cpp.i

.PHONY : src/util/im2col.i

# target to preprocess a source file
src/util/im2col.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/im2col.cpp.i
.PHONY : src/util/im2col.cpp.i

src/util/im2col.s: src/util/im2col.cpp.s

.PHONY : src/util/im2col.s

# target to generate assembly for a file
src/util/im2col.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/im2col.cpp.s
.PHONY : src/util/im2col.cpp.s

src/util/io.o: src/util/io.cpp.o

.PHONY : src/util/io.o

# target to build an object file
src/util/io.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/io.cpp.o
.PHONY : src/util/io.cpp.o

src/util/io.i: src/util/io.cpp.i

.PHONY : src/util/io.i

# target to preprocess a source file
src/util/io.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/io.cpp.i
.PHONY : src/util/io.cpp.i

src/util/io.s: src/util/io.cpp.s

.PHONY : src/util/io.s

# target to generate assembly for a file
src/util/io.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/io.cpp.s
.PHONY : src/util/io.cpp.s

src/util/math_functions.o: src/util/math_functions.cpp.o

.PHONY : src/util/math_functions.o

# target to build an object file
src/util/math_functions.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/math_functions.cpp.o
.PHONY : src/util/math_functions.cpp.o

src/util/math_functions.i: src/util/math_functions.cpp.i

.PHONY : src/util/math_functions.i

# target to preprocess a source file
src/util/math_functions.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/math_functions.cpp.i
.PHONY : src/util/math_functions.cpp.i

src/util/math_functions.s: src/util/math_functions.cpp.s

.PHONY : src/util/math_functions.s

# target to generate assembly for a file
src/util/math_functions.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/math_functions.cpp.s
.PHONY : src/util/math_functions.cpp.s

src/util/upgrade_proto.o: src/util/upgrade_proto.cpp.o

.PHONY : src/util/upgrade_proto.o

# target to build an object file
src/util/upgrade_proto.cpp.o:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/upgrade_proto.cpp.o
.PHONY : src/util/upgrade_proto.cpp.o

src/util/upgrade_proto.i: src/util/upgrade_proto.cpp.i

.PHONY : src/util/upgrade_proto.i

# target to preprocess a source file
src/util/upgrade_proto.cpp.i:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/upgrade_proto.cpp.i
.PHONY : src/util/upgrade_proto.cpp.i

src/util/upgrade_proto.s: src/util/upgrade_proto.cpp.s

.PHONY : src/util/upgrade_proto.s

# target to generate assembly for a file
src/util/upgrade_proto.cpp.s:
	$(MAKE) -f CMakeFiles/caffe.dir/build.make CMakeFiles/caffe.dir/src/util/upgrade_proto.cpp.s
.PHONY : src/util/upgrade_proto.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... caffe"
	@echo "... src/blob.o"
	@echo "... src/blob.i"
	@echo "... src/blob.s"
	@echo "... src/c_api.o"
	@echo "... src/c_api.i"
	@echo "... src/c_api.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/layer_factory_.o"
	@echo "... src/layer_factory_.i"
	@echo "... src/layer_factory_.s"
	@echo "... src/layers/absval_layer.o"
	@echo "... src/layers/absval_layer.i"
	@echo "... src/layers/absval_layer.s"
	@echo "... src/layers/argmax_layer.o"
	@echo "... src/layers/argmax_layer.i"
	@echo "... src/layers/argmax_layer.s"
	@echo "... src/layers/base_conv_layer.o"
	@echo "... src/layers/base_conv_layer.i"
	@echo "... src/layers/base_conv_layer.s"
	@echo "... src/layers/batch_norm_layer.o"
	@echo "... src/layers/batch_norm_layer.i"
	@echo "... src/layers/batch_norm_layer.s"
	@echo "... src/layers/bias_layer.o"
	@echo "... src/layers/bias_layer.i"
	@echo "... src/layers/bias_layer.s"
	@echo "... src/layers/bn_layer.o"
	@echo "... src/layers/bn_layer.i"
	@echo "... src/layers/bn_layer.s"
	@echo "... src/layers/bnll_layer.o"
	@echo "... src/layers/bnll_layer.i"
	@echo "... src/layers/bnll_layer.s"
	@echo "... src/layers/concat_layer.o"
	@echo "... src/layers/concat_layer.i"
	@echo "... src/layers/concat_layer.s"
	@echo "... src/layers/conv_dw_layer.o"
	@echo "... src/layers/conv_dw_layer.i"
	@echo "... src/layers/conv_dw_layer.s"
	@echo "... src/layers/conv_layer.o"
	@echo "... src/layers/conv_layer.i"
	@echo "... src/layers/conv_layer.s"
	@echo "... src/layers/crop_layer.o"
	@echo "... src/layers/crop_layer.i"
	@echo "... src/layers/crop_layer.s"
	@echo "... src/layers/deconv_layer.o"
	@echo "... src/layers/deconv_layer.i"
	@echo "... src/layers/deconv_layer.s"
	@echo "... src/layers/detection_output_layer.o"
	@echo "... src/layers/detection_output_layer.i"
	@echo "... src/layers/detection_output_layer.s"
	@echo "... src/layers/dropout_layer.o"
	@echo "... src/layers/dropout_layer.i"
	@echo "... src/layers/dropout_layer.s"
	@echo "... src/layers/eltwise_layer.o"
	@echo "... src/layers/eltwise_layer.i"
	@echo "... src/layers/eltwise_layer.s"
	@echo "... src/layers/elu_layer.o"
	@echo "... src/layers/elu_layer.i"
	@echo "... src/layers/elu_layer.s"
	@echo "... src/layers/embed_layer.o"
	@echo "... src/layers/embed_layer.i"
	@echo "... src/layers/embed_layer.s"
	@echo "... src/layers/exp_layer.o"
	@echo "... src/layers/exp_layer.i"
	@echo "... src/layers/exp_layer.s"
	@echo "... src/layers/filter_layer.o"
	@echo "... src/layers/filter_layer.i"
	@echo "... src/layers/filter_layer.s"
	@echo "... src/layers/flatten_layer.o"
	@echo "... src/layers/flatten_layer.i"
	@echo "... src/layers/flatten_layer.s"
	@echo "... src/layers/inner_product_layer.o"
	@echo "... src/layers/inner_product_layer.i"
	@echo "... src/layers/inner_product_layer.s"
	@echo "... src/layers/input_layer.o"
	@echo "... src/layers/input_layer.i"
	@echo "... src/layers/input_layer.s"
	@echo "... src/layers/log_layer.o"
	@echo "... src/layers/log_layer.i"
	@echo "... src/layers/log_layer.s"
	@echo "... src/layers/lrn_layer.o"
	@echo "... src/layers/lrn_layer.i"
	@echo "... src/layers/lrn_layer.s"
	@echo "... src/layers/mvn_layer.o"
	@echo "... src/layers/mvn_layer.i"
	@echo "... src/layers/mvn_layer.s"
	@echo "... src/layers/neuron_layer.o"
	@echo "... src/layers/neuron_layer.i"
	@echo "... src/layers/neuron_layer.s"
	@echo "... src/layers/normalize_layer.o"
	@echo "... src/layers/normalize_layer.i"
	@echo "... src/layers/normalize_layer.s"
	@echo "... src/layers/parameter_layer.o"
	@echo "... src/layers/parameter_layer.i"
	@echo "... src/layers/parameter_layer.s"
	@echo "... src/layers/permute_layer.o"
	@echo "... src/layers/permute_layer.i"
	@echo "... src/layers/permute_layer.s"
	@echo "... src/layers/pooling_layer.o"
	@echo "... src/layers/pooling_layer.i"
	@echo "... src/layers/pooling_layer.s"
	@echo "... src/layers/power_layer.o"
	@echo "... src/layers/power_layer.i"
	@echo "... src/layers/power_layer.s"
	@echo "... src/layers/prelu_layer.o"
	@echo "... src/layers/prelu_layer.i"
	@echo "... src/layers/prelu_layer.s"
	@echo "... src/layers/prior_box_layer.o"
	@echo "... src/layers/prior_box_layer.i"
	@echo "... src/layers/prior_box_layer.s"
	@echo "... src/layers/proposal_layer.o"
	@echo "... src/layers/proposal_layer.i"
	@echo "... src/layers/proposal_layer.s"
	@echo "... src/layers/psroi_pooling_layer.o"
	@echo "... src/layers/psroi_pooling_layer.i"
	@echo "... src/layers/psroi_pooling_layer.s"
	@echo "... src/layers/reduction_layer.o"
	@echo "... src/layers/reduction_layer.i"
	@echo "... src/layers/reduction_layer.s"
	@echo "... src/layers/relu_layer.o"
	@echo "... src/layers/relu_layer.i"
	@echo "... src/layers/relu_layer.s"
	@echo "... src/layers/reshape_layer.o"
	@echo "... src/layers/reshape_layer.i"
	@echo "... src/layers/reshape_layer.s"
	@echo "... src/layers/roi_pooling_layer.o"
	@echo "... src/layers/roi_pooling_layer.i"
	@echo "... src/layers/roi_pooling_layer.s"
	@echo "... src/layers/scale_layer.o"
	@echo "... src/layers/scale_layer.i"
	@echo "... src/layers/scale_layer.s"
	@echo "... src/layers/shuffle_channel_layer.o"
	@echo "... src/layers/shuffle_channel_layer.i"
	@echo "... src/layers/shuffle_channel_layer.s"
	@echo "... src/layers/sigmoid_layer.o"
	@echo "... src/layers/sigmoid_layer.i"
	@echo "... src/layers/sigmoid_layer.s"
	@echo "... src/layers/slice_layer.o"
	@echo "... src/layers/slice_layer.i"
	@echo "... src/layers/slice_layer.s"
	@echo "... src/layers/softmax_layer.o"
	@echo "... src/layers/softmax_layer.i"
	@echo "... src/layers/softmax_layer.s"
	@echo "... src/layers/split_layer.o"
	@echo "... src/layers/split_layer.i"
	@echo "... src/layers/split_layer.s"
	@echo "... src/layers/spp_layer.o"
	@echo "... src/layers/spp_layer.i"
	@echo "... src/layers/spp_layer.s"
	@echo "... src/layers/tanh_layer.o"
	@echo "... src/layers/tanh_layer.i"
	@echo "... src/layers/tanh_layer.s"
	@echo "... src/layers/threshold_layer.o"
	@echo "... src/layers/threshold_layer.i"
	@echo "... src/layers/threshold_layer.s"
	@echo "... src/layers/tile_layer.o"
	@echo "... src/layers/tile_layer.i"
	@echo "... src/layers/tile_layer.s"
	@echo "... src/net.o"
	@echo "... src/net.i"
	@echo "... src/net.s"
	@echo "... src/profiler.o"
	@echo "... src/profiler.i"
	@echo "... src/profiler.s"
	@echo "... src/proto/caffe.pb.o"
	@echo "... src/proto/caffe.pb.i"
	@echo "... src/proto/caffe.pb.s"
	@echo "... src/syncedmem.o"
	@echo "... src/syncedmem.i"
	@echo "... src/syncedmem.s"
	@echo "... src/util/bbox_util.o"
	@echo "... src/util/bbox_util.i"
	@echo "... src/util/bbox_util.s"
	@echo "... src/util/im2col.o"
	@echo "... src/util/im2col.i"
	@echo "... src/util/im2col.s"
	@echo "... src/util/io.o"
	@echo "... src/util/io.i"
	@echo "... src/util/io.s"
	@echo "... src/util/math_functions.o"
	@echo "... src/util/math_functions.i"
	@echo "... src/util/math_functions.s"
	@echo "... src/util/upgrade_proto.o"
	@echo "... src/util/upgrade_proto.i"
	@echo "... src/util/upgrade_proto.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

